name: domnode
description: A client-side library to easily change and traverse DOM documents.
version: 1.1.0
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/soloproyectos-dart/domnode
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: ">=0.10.0 <0.11.0"
